<?php

namespace BitCode\FI\Core\Util;

final class AllTriggersName
{
    public static $allTriggersName =
    [
        'ARForm'            => ['name' => 'ARForm', 'isPro' => true],
        'ARMember'          => ['name' => 'ARMember', 'isPro' => true],
        'AcademyLms'        => ['name' => 'AcademyLms', 'isPro' => true],
        'ActionHook'        => ['name' => 'ActionHook', 'isPro' => false],
        'Affiliate'         => ['name' => 'Affiliate', 'isPro' => true],
        'Amelia'            => ['name' => 'Amelia', 'isPro' => true],
        'Beaver'            => ['name' => 'Beaver', 'isPro' => true],
        'BitAssist'         => ['name' => 'BitAssist', 'isPro' => false],
        'BitForm'           => ['name' => 'BitForm', 'isPro' => false],
        'Breakdance'        => ['name' => 'Breakdance', 'isPro' => true],
        'Bricks'            => ['name' => 'Bricks', 'isPro' => true],
        'Brizy'             => ['name' => 'Brizy', 'isPro' => true],
        'BuddyBoss'         => ['name' => 'BuddyBoss', 'isPro' => true],
        'CF7'               => ['name' => 'CF7', 'isPro' => false],
        'CartFlow'          => ['name' => 'CartFlow', 'isPro' => true],
        'CustomTrigger'     => ['name' => 'CustomTrigger', 'isPro' => false],
        'Divi'              => ['name' => 'Divi', 'isPro' => true],
        'EDD'               => ['name' => 'EDD', 'isPro' => true],
        'EVF'               => ['name' => 'EVF', 'isPro' => true],
        'Elementor'         => ['name' => 'Elementor', 'isPro' => false],
        'EssentialBlocks'   => ['name' => 'EssentialBlocks', 'isPro' => true],
        'FF'                => ['name' => 'FF', 'isPro' => true],
        'FluentCrm'         => ['name' => 'FluentCrm', 'isPro' => true],
        'FluentSupport'     => ['name' => 'FluentSupport', 'isPro' => true],
        'FormCraft'         => ['name' => 'FormCraft', 'isPro' => true],
        'Formidable'        => ['name' => 'Formidable', 'isPro' => true],
        'Forminator'        => ['name' => 'Forminator', 'isPro' => true],
        'GF'                => ['name' => 'GF', 'isPro' => true],
        'GamiPress'         => ['name' => 'GamiPress', 'isPro' => true],
        'GiveWp'            => ['name' => 'GiveWp', 'isPro' => true],
        'Groundhogg'        => ['name' => 'Groundhogg', 'isPro' => true],
        'Happy'             => ['name' => 'Happy', 'isPro' => true],
        'JetEngine'         => ['name' => 'JetEngine', 'isPro' => true],
        'JetForm'           => ['name' => 'JetForm', 'isPro' => true],
        'Kadence'           => ['name' => 'Kadence', 'isPro' => true],
        'KaliForms'         => ['name' => 'KaliForms', 'isPro' => true],
        'LearnDash'         => ['name' => 'LearnDash', 'isPro' => true],
        'LifterLms'         => ['name' => 'LifterLms', 'isPro' => true],
        'MailPoet'          => ['name' => 'MailPoet', 'isPro' => true],
        'MasterStudyLms'    => ['name' => 'MasterStudyLms', 'isPro' => true],
        'Memberpress'       => ['name' => 'Memberpress', 'isPro' => true],
        'Met'               => ['name' => 'Met', 'isPro' => true],
        'MetaBox'           => ['name' => 'MetaBox', 'isPro' => true],
        'NF'                => ['name' => 'NF', 'isPro' => true],
        'OptinMonster'      => ['name' => 'OptinMonster', 'isPro' => true],
        'PaidMembershipPro' => ['name' => 'PaidMembershipPro', 'isPro' => true],
        'PiotnetAddon'      => ['name' => 'PiotnetAddon', 'isPro' => true],
        'PiotnetAddonForm'  => ['name' => 'PiotnetAddonForm', 'isPro' => true],
        'PiotnetForms'      => ['name' => 'PiotnetForms', 'isPro' => true],
        'Rafflepress'       => ['name' => 'Rafflepress', 'isPro' => true],
        'RestrictContent'   => ['name' => 'RestrictContent', 'isPro' => true],
        'SliceWp'           => ['name' => 'SliceWp', 'isPro' => true],
        'SolidAffiliate'    => ['name' => 'SolidAffiliate', 'isPro' => true],
        'Spectra'           => ['name' => 'Spectra', 'isPro' => true],
        'StudioCart'        => ['name' => 'StudioCart', 'isPro' => true],
        'SureCart'          => ['name' => 'SureCart', 'isPro' => true],
        'ThriveApprentice'  => ['name' => 'ThriveApprentice', 'isPro' => true],
        'Tripetto'          => ['name' => 'Tripetto', 'isPro' => true],
        'TutorLms'          => ['name' => 'TutorLms', 'isPro' => true],
        'UltimateMember'    => ['name' => 'UltimateMember', 'isPro' => true],
        'WC'                => ['name' => 'WC', 'isPro' => false],
        'WPCourseware'      => ['name' => 'WPCourseware', 'isPro' => true],
        'WPEF'              => ['name' => 'WPEF', 'isPro' => true],
        'WPF'               => ['name' => 'WPF', 'isPro' => false],
        'WPFunnels'         => ['name' => 'WPFunnels', 'isPro' => true],
        'WSForm'            => ['name' => 'WSForm', 'isPro' => true],
        'WeForms'           => ['name' => 'WeForms', 'isPro' => true],
        'Webhook'           => ['name' => 'Webhook', 'isPro' => false],
    ];
}