<?php

namespace BitCode\FI\Core\Util;

final class AllTriggersName
{
    public static function allTriggersName()
    {
        return [
            'AcademyLms'        => ['name' => __('Academy Lms', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'ActionHook'        => ['name' => __('Action Hook', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'Affiliate'         => ['name' => __('Affiliate', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'Amelia'            => ['name' => __('Amelia', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'ARForm'            => ['name' => __('ARForm', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'ARMember'          => ['name' => __('ARMember', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'Beaver'            => ['name' => __('Beaver', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'BitAssist'         => ['name' => __('Bit  Assist', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'Breakdance'        => ['name' => __('Breakdance', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'Bricks'            => ['name' => __('Bricks', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'Bricksforge'       => ['name' => __('Bricksforge', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'Brizy'             => ['name' => __('Brizy', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'BuddyBoss'         => ['name' => __('BuddyBoss', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'CartFlow'          => ['name' => __('CartFlow', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'Coblocks'          => ['name' => __('CoBlocks Form', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'Divi'              => ['name' => __('Divi', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'Dokan'             => ['name' => __('Dokan', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'EDD'               => ['name' => __('Easy Digital Downloads', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'EssentialBlocks'   => ['name' => __('Essential Blocks', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'EVF'               => ['name' => __('Everest Forms', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'FF'                => ['name' => __('Fluent Forms', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'FluentBooking'     => ['name' => __('Fluent Booking', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'FluentCrm'         => ['name' => __('Fluent CRM', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'FluentSupport'     => ['name' => __('Fluent Support', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'FormCraft'         => ['name' => __('FormCraft3', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'Formidable'        => ['name' => __('Formidable', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'Forminator'        => ['name' => __('Forminator', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'GamiPress'         => ['name' => __('GamiPress', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'GF'                => ['name' => __('Gravity Forms', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'GiveWp'            => ['name' => __('GiveWp', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'Groundhogg'        => ['name' => __('Groundhogg', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'gutenaForms'       => ['name' => __('Gutena Forms', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'Happy'             => ['name' => __('Happy Forms', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'Hustle'            => ['name' => __('Hustle', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'JetEngine'         => ['name' => __('JetEngine', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'JetForm'           => ['name' => __('JetForm Builder', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'Kadence'           => ['name' => __('Kadence Blocks Form', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'KaliForms'         => ['name' => __('Kali Forms', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'LearnDash'         => ['name' => __('LearnDash LMS', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'LifterLms'         => ['name' => __('LifterLMS', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'MailPoet'          => ['name' => __('MailPoet', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'Mailster'          => ['name' => __('Mailster', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'MasterStudyLms'    => ['name' => __('MasterStudyLms', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'Memberpress'       => ['name' => __('Memberpress', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'Met'               => ['name' => __('Met Form', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'MetaBox'           => ['name' => __('MB Frontend Submission', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'NF'                => ['name' => __('Ninja Forms', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'OptinMonster'      => ['name' => __('OptinMonster', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'PaidMembershipPro' => ['name' => __('Paid Membership Pro', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'PiotnetAddon'      => ['name' => __('PiotnetAddon', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'PiotnetAddonForm'  => ['name' => __('PiotnetAddonForm', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'PiotnetForms'      => ['name' => __('Piotnet Forms', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'PopupMaker'        => ['name' => __('Popup Maker', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'Post'              => ['name' => __('Post', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'Rafflepress'       => ['name' => __('Rafflepress', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'Rafflepress'       => ['name' => __('Rafflepress', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'Registration'      => ['name' => __('User Registration', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'RestrictContent'   => ['name' => __('Restrict Content', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'SiteOriginWidgets' => ['name' => __('SiteOrigin Widgets', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'SliceWp'           => ['name' => __('SliceWp', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'SolidAffiliate'    => ['name' => __('Solid Affiliate', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'Spectra'           => ['name' => __('Spectra', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'StudioCart'        => ['name' => __('StudioCart', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'SureCart'          => ['name' => __('SureCart', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'SureForms'         => ['name' => __('SureForms', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'SureMembers'       => ['name' => __('SureMembers', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'ThriveApprentice'  => ['name' => __('ThriveApprentice', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'Tripetto'          => ['name' => __('Tripetto', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'TutorLms'          => ['name' => __('Tutor LMS', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'UltimateMember'    => ['name' => __('UltimateMember', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'Webhook'           => ['name' => __('Webhook', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'WeForms'           => ['name' => __('WeForms', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'WPCourseware'      => ['name' => __('WP Courseware', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'WPEF'              => ['name' => __('eForm', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'WPForo'            => ['name' => __('wpForo Forum', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'WPFunnels'         => ['name' => __('WPFunnels', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'WPJobManager'      => ['name' => __('WP Job Manager', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
            'WSForm'            => ['name' => __('WSForm', 'bit-integrations'), 'isPro' => true, 'is_active' => false],
        ];
    }
}
